In [1]:
import pandas as pd

loans = pd.read_csv("../_datasets/loans.csv")
loans = loans[["loan_amnt", "funded_amnt", "int_rate", "title"]]
loans.head(8)

/var/folders/gc/0752xrm56pnf0r0dsrn5370c0000gr/T/ipykernel_85886/3954469040.py:3: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  loans = pd.read_csv("../_datasets/loans.csv")

   loan_amnt  funded_amnt int_rate                                  title
0       5000         5000   10.65%                               Computer
1       2500         2500   15.27%                                   bike
2       2400         2400   15.96%                   real estate business
3      10000        10000   13.49%                               personel
4       3000         3000   12.69%                               Personal
5       5000         5000    7.90%  My wedding loan I promise to pay back
6       7000         7000   15.96%                                   Loan
7       3000         3000   18.64%                        Car Downpayment

In [ ]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(loans):
    # Derive column 'derivedCol' from column: 'int_rate'
    # Transform based on the following examples:
    #    int_rate    Output
    # 1: "10.65%" => "10.65"
    loans.insert(3, "interest rate", loans["int_rate"].str.replace("%", ""))
    # Change column type to float64 for column: 'interest rate'
    loans = loans.astype({'interest rate': 'float64'})
    return loans

loans_clean = clean_data(loans.copy())
loans_clean.head()